language: bash

services: docker

env:
  - BRANCH=abc
  - BRANCH=btc1
  - BRANCH=classic
  - BRANCH=core
  - BRANCH=unlimited
  - BRANCH=xt

script:
  - make validate
  - make test

after_script:
  - docker images

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push lrabiet/bitcoin;
